# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('fishType', models.CharField(max_length=128)),
                ('description', models.CharField(default='Fish Description', max_length=20000)),
                ('area', models.CharField(default='The Sea', max_length=200)),
                ('sustainability', models.IntegerField(default=3)),
                ('image', models.ImageField(upload_to='static/fish_images')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=9999, null=True)),
                ('ingredients', models.CharField(max_length=9999, null=True)),
                ('method', models.CharField(max_length=9999, null=True)),
                ('time', models.IntegerField(null=True)),
                ('serves', models.IntegerField(null=True)),
                ('avgRating', models.FloatField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='recipe_images')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishydishy.Fish')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=5)),
                ('comment', models.CharField(max_length=2000, null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishydishy.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
