# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.CharField(default='Admin', max_length=128),
        ),
    ]
