# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.FloatField(default=1),
        ),
    ]
