# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0002_recipe_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
