# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0002_auto_20180307_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='description',
            field=models.CharField(default='Fish Description', max_length=20000),
        ),
    ]
