# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0003_remove_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='avgRating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipe_images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
