# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0005_auto_20180307_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
