# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0006_auto_20180307_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=1280, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=1280, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
