# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0007_auto_20180307_1345'),
        ('fishydishy', '0003_auto_20180307_1309'),
    ]

    operations = [
    ]
