# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0009_remove_fish_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='area',
            field=models.CharField(default='The Sea', max_length=200),
        ),
    ]
