# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0011_merge_20180310_1417'),
        ('fishydishy', '0012_recipe_user'),
    ]

    operations = [
    ]
