# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0013_merge_20180310_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
