# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0013_merge_20180310_1537'),
        ('fishydishy', '0013_merge_20180310_1546'),
    ]

    operations = [
    ]
