# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0011_merge_20180310_1333'),
        ('fishydishy', '0014_auto_20180310_1624'),
        ('fishydishy', '0014_merge_20180310_1616'),
    ]

    operations = [
    ]
