# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0016_auto_20180313_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
