# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0016_auto_20180313_1644'),
        ('fishydishy', '0014_merge_20180310_1654'),
    ]

    operations = [
    ]
