# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0017_auto_20180314_1240'),
        ('fishydishy', '0017_review_comment'),
    ]

    operations = [
    ]
