# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0017_review_comment'),
        ('fishydishy', '0019_auto_20180314_1304'),
    ]

    operations = [
    ]
