# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0020_merge_20180314_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cost',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
