# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0021_auto_20180314_1452'),
        ('fishydishy', '0021_auto_20180314_1418'),
    ]

    operations = [
    ]
