# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0022_merge_20180314_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
