# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0023_recipe_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cost',
        ),
    ]
