# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0024_remove_recipe_cost'),
        ('fishydishy', '0018_merge_20180314_1304'),
    ]

    operations = [
    ]
