# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0025_merge_20180315_1251'),
        ('fishydishy', '0025_merge_20180314_1824'),
    ]

    operations = [
    ]
