# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0026_merge_20180315_1350'),
        ('fishydishy', '0026_merge_20180315_1321'),
    ]

    operations = [
    ]
