# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishydishy', '0027_merge_20180315_1410'),
        ('fishydishy', '0027_merge_20180315_1356'),
    ]

    operations = [
    ]
